# Generated by Django 3.2.24 on 2024-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paruluserapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hdpmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=100)),
                ('trestbps', models.CharField(max_length=100)),
                ('chol', models.CharField(max_length=100)),
                ('fbs', models.CharField(max_length=100)),
                ('restecg', models.CharField(max_length=100)),
                ('thalach', models.CharField(max_length=100)),
                ('exang', models.CharField(max_length=100)),
                ('oldpeak', models.CharField(max_length=100)),
                ('slope', models.CharField(max_length=100)),
                ('ca', models.CharField(max_length=100)),
                ('thal', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('custom_predictions', models.CharField(max_length=100)),
            ],
        ),
    ]
