# Generated by Django 3.2.24 on 2024-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paruluserapp', '0002_hdpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='bdpmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('menopause', models.CharField(max_length=100)),
                ('Tumor', models.CharField(max_length=100)),
                ('InvNodes', models.CharField(max_length=100)),
                ('Breast', models.CharField(max_length=100)),
                ('Metastasis', models.CharField(max_length=100)),
                ('BreastQuadrant', models.CharField(max_length=100)),
                ('History', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('custom_predictions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dpmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.CharField(max_length=100)),
                ('glucose', models.CharField(max_length=100)),
                ('bloodpressure', models.CharField(max_length=100)),
                ('skinthickness', models.CharField(max_length=100)),
                ('insulin', models.CharField(max_length=100)),
                ('bmi', models.CharField(max_length=100)),
                ('diabetespedigreefunction', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('custom_predictions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kdpmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.CharField(max_length=100)),
                ('sg', models.CharField(max_length=100)),
                ('al', models.CharField(max_length=100)),
                ('su', models.CharField(max_length=100)),
                ('rbc', models.CharField(max_length=100)),
                ('bu', models.CharField(max_length=100)),
                ('sc', models.CharField(max_length=100)),
                ('sod', models.CharField(max_length=100)),
                ('pot', models.CharField(max_length=100)),
                ('hemo', models.CharField(max_length=100)),
                ('wbcc', models.CharField(max_length=100)),
                ('rbcc', models.CharField(max_length=100)),
                ('htn', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('custom_predictions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ldpmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Total_Bilirubin', models.CharField(max_length=100)),
                ('Direct_Bilirubin', models.CharField(max_length=100)),
                ('Alkaline_Phosphotase', models.CharField(max_length=100)),
                ('Alamine_Aminotransferase', models.CharField(max_length=100)),
                ('Aspartate_Aminotransferase', models.CharField(max_length=100)),
                ('Total_Protiens', models.CharField(max_length=100)),
                ('Albumin', models.CharField(max_length=100)),
                ('Albumin_and_Globulin_Ratio', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('custom_predictions', models.CharField(max_length=100)),
            ],
        ),
    ]
